### ISSUE TITLE
Can you please help to get the CTF Code and Virtual machine for leaarning Python.

### ISSUE THREAD

**Issue by bganeshmail** [yamakira/art-of-packet-crafting-with-scapy#1]
All:

I found this excellent Link and part of Null Con group .

Can you please help to get the CTF Code and Virtual machine for learning Python.

**Comment by 0xbharath** [comment]
I will be providing the CTF code and the labs after the first delivery at Null, Bangalore which is most probably on 5th Nov 2016.

**Comment by 0xbharath** [comment]
The class VM is available here https://archive.org/details/pysos_class3_labs_32bit.7z
