### ISSUE TITLE
Site not found 404

### ISSUE THREAD

**Issue by mikeybro** [yamakira/art-of-packet-crafting-with-scapy#4]
I am trying to access the material on https://yamakira.github.io/art-of-packet-crafting-with-scapy/network_recon/service_discovery/index.html

but i get the 404 error, is there any feedback you can provide with the issue?

**Comment by 0xbharath** [comment]
That is because I have changed my twitter handle. You can access the notes at - https://0xbharath.github.io/art-of-packet-crafting-with-scapy/network_recon/service_discovery/index.html
