### ISSUE TITLE
some faults of  art-of-packet-crafting-with-scapy

### ISSUE THREAD

**Issue by dy20082250** [yamakira/art-of-packet-crafting-with-scapy#5]
I read the doc and find some spelling faults, for example,
https://0xbharath.github.io/art-of-packet-crafting-with-scapy/scapy/sending_recieving/index.html
![Snip20200605_1](https://user-images.githubusercontent.com/10095467/83819056-7e0ced80-a6fb-11ea-8442-a91749934029.png)

can i do something to fix these spelling faults?

**Comment by 0xbharath** [comment]
Thanks for the offer. I have created this repo few years ago. I don't have the source markdown files currently. I will try and port this document into a mdbook/gitbook. You can contribute then.

**Comment by dy20082250** [comment]
ok, waiting for good news

**Comment by dy20082250** [comment]
> Thanks for the offer. I have created this repo few years ago. I don't have the source markdown files currently. I will try and port this document into a mdbook/gitbook. You can contribute then.
ok, waiting for good news

**Comment by 0xbharath** [comment]
I have ported the documentation to mdbook. The documentation is under `documentation` branch and it is written in markdown. You can basically make any changes you need to and raise a PR.

New documentation home - https://scapy.disruptivelabs.in/
